package com.ladddd.myandroidarch.model.dao;

import com.ladddd.myandroidarch.model.GankMeiziInfo;
import com.ladddd.myandroidarch.model.GankMeiziResult;
import com.ladddd.mylib.utils.JsonUtils;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by 陈伟达 on 2017/6/20.
 */

@Entity
public class GankMeiziDao {

    @Id
    public long id;

    public boolean error;

    public String gankMeiziListString;


    public GankMeiziDao(int page, GankMeiziResult result) {
        id = page;
        error = result.error;
        gankMeiziListString = JsonUtils.getJsonString(result.gankMeizis);
    }


    @Generated(168056277)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public GankMeiziDao(long id, boolean error, String gankMeiziListString) {
        this.id = id;
        this.error = error;
        this.gankMeiziListString = gankMeiziListString;
    }


    @Generated(161255320)
    public GankMeiziDao() {
    }
}
