package com.ladddd.myandroidarch.model.dao;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by 陈伟达 on 2017/7/19.
 */

@Entity
public class TestDao {

    @Id
    private long id;

    private String key;

    private String value;

    public TestDao(String key, String value) {
        this.key = key;
        this.value = value;
    }

    @Generated(1530826894)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public TestDao(long id, String key, String value) {
        this.id = id;
        this.key = key;
        this.value = value;
    }

    @Generated(1692582752)
    public TestDao() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
